In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
sent=[
    "Python is an easy-to-learn programming language.",
    "It is widely used in data science and AI.",
    "Python has a clean and readable syntax.",
    "It supports multiple programming paradigms.",
    "Libraries like NumPy and TensorFlow make Python powerful.",
    "Python has a massive and helpful developer community."

]

In [3]:
sent

['Python is an easy-to-learn programming language.',
 'It is widely used in data science and AI.',
 'Python has a clean and readable syntax.',
 'It supports multiple programming paradigms.',
 'Libraries like NumPy and TensorFlow make Python powerful.',
 'Python has a massive and helpful developer community.']

In [4]:
## Define   The Vocabulary Size
voc_size=10000


In [5]:
## One Hot Representation

one_hot_rep=[one_hot(words,voc_size)for words in sent]
one_hot_rep

[[8300, 6859, 3476, 4516, 225, 3889, 3143, 3502],
 [8025, 6859, 477, 7123, 4277, 2528, 9687, 290, 2470],
 [8300, 9598, 801, 8330, 290, 5125, 5408],
 [8025, 5202, 9084, 3143, 4168],
 [1911, 8164, 5667, 290, 6231, 7675, 8300, 4107],
 [8300, 9598, 801, 2782, 290, 312, 6563, 8891]]

In [7]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential 

In [8]:
import numpy as np


In [14]:
## SENTENCE SHOULD BE OF SAME LENGTH
sent_length=8
Embedded_doc=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(Embedded_doc)

[[8300 6859 3476 4516  225 3889 3143 3502]
 [6859  477 7123 4277 2528 9687  290 2470]
 [   0 8300 9598  801 8330  290 5125 5408]
 [   0    0    0 8025 5202 9084 3143 4168]
 [1911 8164 5667  290 6231 7675 8300 4107]
 [8300 9598  801 2782  290  312 6563 8891]]


In [15]:
## Feature_Representation
dim=10


In [16]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
model.predict(Embedded_doc)

1/1 [==============================] - 0s 263ms/step


array([[[ 0.03536203,  0.0397747 , -0.04388806, -0.01217251,
         -0.04406381, -0.00973215,  0.01684603,  0.04994042,
          0.01131419,  0.01127441],
        [-0.0336713 ,  0.02004743,  0.00675685, -0.01428847,
          0.04605133, -0.04200087, -0.00395349,  0.02321503,
          0.02491293,  0.02424036],
        [-0.0433722 ,  0.04563776,  0.02052223, -0.04336196,
         -0.02589662, -0.02669678, -0.00418498, -0.00614242,
         -0.00608147,  0.03161455],
        [-0.0459293 ,  0.02749005,  0.02126763, -0.03478011,
          0.01685247,  0.04499556, -0.0464903 ,  0.02225986,
         -0.01274097,  0.00256851],
        [-0.01522087, -0.03251467,  0.04295849, -0.00798993,
         -0.01577745, -0.00027838,  0.03432133,  0.01032624,
          0.01573965,  0.04256293],
        [-0.00329279, -0.03097453,  0.03183463, -0.04382585,
          0.04304972,  0.03859253,  0.03046581, -0.02217307,
          0.01459768,  0.04498051],
        [ 0.03606284, -0.00909855,  0.03010683, -0.0

In [19]:
Embedded_doc[0]

array([8300, 6859, 3476, 4516,  225, 3889, 3143, 3502])